services:
  postgres:
    image: postgres:14-alpine
    container_name: donorbox-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=a
      - POSTGRES_DB=donorbox
    ports:
      - "5432:5432"

  weaviate:
    image: cr.weaviate.io/semitechnologies/weaviate:1.27.6
    container_name: donorbox-vector-db
    ports:
      - 8080:8080
      - 50051:50051
    restart: on-failure:0

  backend:
    image: dungnt07/donorbox-backend:prod
    container_name: donorbox-backend
    expose:
      - "4000"
    env_file:
      - ./.env.prod
    depends_on:
      - postgres
      - weaviate
    entrypoint: ["/app/wait-for.sh", "postgres:5432", "--", "/api"]

  client:
    image: dungnt07/donorbox-client:prod
    container_name: donorbox-client
    expose:
      - "80"

  dashboard:
    image: dungnt07/donorbox-dashboard:prod
    container_name: donorbox-dashboard
    expose:
      - "80"

  nginx:
    image: nginx:latest
    container_name: donorbox-nginx
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx/certs:/etc/nginx/certs:ro
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - client
      - dashboard
