version: "3.8"

services:
  postgres:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=a
      - POSTGRES_DB=donorbox
    ports:
      - "5432:5432"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

  backend:
    image: dungnt07/donorbox-backend
    container_name: donorbox-backend
    ports:
      - "4000:4000"
    env_file:
      - ./.env.prod
    depends_on:
      - postgres
    entrypoint: ["/app/wait-for.sh", "postgres:5432", "--", "/api"]

  client:
    image: dungnt07/donorbox-client
    container_name: donorbox-client
    ports:
      - "4001:80"

  dashboard:
    image: dungnt07/donorbox-dashboard
    container_name: donorbox-dashboard
    ports:
      - "4002:80"
