// Code generated by mockery v2.46.3. DO NOT EDIT.

package mocks

import (
	context "context"

	db "github.com/kanowfy/donorbox/internal/db"
	mock "github.com/stretchr/testify/mock"
)

// Querier is an autogenerated mock type for the Querier type
type Querier struct {
	mock.Mock
}

type Querier_Expecter struct {
	mock *mock.Mock
}

func (_m *Querier) EXPECT() *Querier_Expecter {
	return &Querier_Expecter{mock: &_m.Mock}
}

// ActivateUser provides a mock function with given fields: ctx, id
func (_m *Querier) ActivateUser(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for ActivateUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Querier_ActivateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ActivateUser'
type Querier_ActivateUser_Call struct {
	*mock.Call
}

// ActivateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *Querier_Expecter) ActivateUser(ctx interface{}, id interface{}) *Querier_ActivateUser_Call {
	return &Querier_ActivateUser_Call{Call: _e.mock.On("ActivateUser", ctx, id)}
}

func (_c *Querier_ActivateUser_Call) Run(run func(ctx context.Context, id int64)) *Querier_ActivateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *Querier_ActivateUser_Call) Return(_a0 error) *Querier_ActivateUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Querier_ActivateUser_Call) RunAndReturn(run func(context.Context, int64) error) *Querier_ActivateUser_Call {
	_c.Call.Return(run)
	return _c
}

// CreateBacking provides a mock function with given fields: ctx, arg
func (_m *Querier) CreateBacking(ctx context.Context, arg db.CreateBackingParams) (db.Backing, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateBacking")
	}

	var r0 db.Backing
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateBackingParams) (db.Backing, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateBackingParams) db.Backing); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.Backing)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.CreateBackingParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Querier_CreateBacking_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBacking'
type Querier_CreateBacking_Call struct {
	*mock.Call
}

// CreateBacking is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.CreateBackingParams
func (_e *Querier_Expecter) CreateBacking(ctx interface{}, arg interface{}) *Querier_CreateBacking_Call {
	return &Querier_CreateBacking_Call{Call: _e.mock.On("CreateBacking", ctx, arg)}
}

func (_c *Querier_CreateBacking_Call) Run(run func(ctx context.Context, arg db.CreateBackingParams)) *Querier_CreateBacking_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.CreateBackingParams))
	})
	return _c
}

func (_c *Querier_CreateBacking_Call) Return(_a0 db.Backing, _a1 error) *Querier_CreateBacking_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Querier_CreateBacking_Call) RunAndReturn(run func(context.Context, db.CreateBackingParams) (db.Backing, error)) *Querier_CreateBacking_Call {
	_c.Call.Return(run)
	return _c
}

// CreateEscrowUser provides a mock function with given fields: ctx, arg
func (_m *Querier) CreateEscrowUser(ctx context.Context, arg db.CreateEscrowUserParams) (db.EscrowUser, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateEscrowUser")
	}

	var r0 db.EscrowUser
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateEscrowUserParams) (db.EscrowUser, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateEscrowUserParams) db.EscrowUser); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.EscrowUser)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.CreateEscrowUserParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Querier_CreateEscrowUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateEscrowUser'
type Querier_CreateEscrowUser_Call struct {
	*mock.Call
}

// CreateEscrowUser is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.CreateEscrowUserParams
func (_e *Querier_Expecter) CreateEscrowUser(ctx interface{}, arg interface{}) *Querier_CreateEscrowUser_Call {
	return &Querier_CreateEscrowUser_Call{Call: _e.mock.On("CreateEscrowUser", ctx, arg)}
}

func (_c *Querier_CreateEscrowUser_Call) Run(run func(ctx context.Context, arg db.CreateEscrowUserParams)) *Querier_CreateEscrowUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.CreateEscrowUserParams))
	})
	return _c
}

func (_c *Querier_CreateEscrowUser_Call) Return(_a0 db.EscrowUser, _a1 error) *Querier_CreateEscrowUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Querier_CreateEscrowUser_Call) RunAndReturn(run func(context.Context, db.CreateEscrowUserParams) (db.EscrowUser, error)) *Querier_CreateEscrowUser_Call {
	_c.Call.Return(run)
	return _c
}

// CreateMilestone provides a mock function with given fields: ctx, arg
func (_m *Querier) CreateMilestone(ctx context.Context, arg db.CreateMilestoneParams) (db.Milestone, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateMilestone")
	}

	var r0 db.Milestone
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateMilestoneParams) (db.Milestone, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateMilestoneParams) db.Milestone); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.Milestone)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.CreateMilestoneParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Querier_CreateMilestone_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateMilestone'
type Querier_CreateMilestone_Call struct {
	*mock.Call
}

// CreateMilestone is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.CreateMilestoneParams
func (_e *Querier_Expecter) CreateMilestone(ctx interface{}, arg interface{}) *Querier_CreateMilestone_Call {
	return &Querier_CreateMilestone_Call{Call: _e.mock.On("CreateMilestone", ctx, arg)}
}

func (_c *Querier_CreateMilestone_Call) Run(run func(ctx context.Context, arg db.CreateMilestoneParams)) *Querier_CreateMilestone_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.CreateMilestoneParams))
	})
	return _c
}

func (_c *Querier_CreateMilestone_Call) Return(_a0 db.Milestone, _a1 error) *Querier_CreateMilestone_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Querier_CreateMilestone_Call) RunAndReturn(run func(context.Context, db.CreateMilestoneParams) (db.Milestone, error)) *Querier_CreateMilestone_Call {
	_c.Call.Return(run)
	return _c
}

// CreateMilestoneCompletion provides a mock function with given fields: ctx, arg
func (_m *Querier) CreateMilestoneCompletion(ctx context.Context, arg db.CreateMilestoneCompletionParams) (db.MilestoneCompletion, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateMilestoneCompletion")
	}

	var r0 db.MilestoneCompletion
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateMilestoneCompletionParams) (db.MilestoneCompletion, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateMilestoneCompletionParams) db.MilestoneCompletion); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.MilestoneCompletion)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.CreateMilestoneCompletionParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Querier_CreateMilestoneCompletion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateMilestoneCompletion'
type Querier_CreateMilestoneCompletion_Call struct {
	*mock.Call
}

// CreateMilestoneCompletion is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.CreateMilestoneCompletionParams
func (_e *Querier_Expecter) CreateMilestoneCompletion(ctx interface{}, arg interface{}) *Querier_CreateMilestoneCompletion_Call {
	return &Querier_CreateMilestoneCompletion_Call{Call: _e.mock.On("CreateMilestoneCompletion", ctx, arg)}
}

func (_c *Querier_CreateMilestoneCompletion_Call) Run(run func(ctx context.Context, arg db.CreateMilestoneCompletionParams)) *Querier_CreateMilestoneCompletion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.CreateMilestoneCompletionParams))
	})
	return _c
}

func (_c *Querier_CreateMilestoneCompletion_Call) Return(_a0 db.MilestoneCompletion, _a1 error) *Querier_CreateMilestoneCompletion_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Querier_CreateMilestoneCompletion_Call) RunAndReturn(run func(context.Context, db.CreateMilestoneCompletionParams) (db.MilestoneCompletion, error)) *Querier_CreateMilestoneCompletion_Call {
	_c.Call.Return(run)
	return _c
}

// CreateProject provides a mock function with given fields: ctx, arg
func (_m *Querier) CreateProject(ctx context.Context, arg db.CreateProjectParams) (db.Project, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateProject")
	}

	var r0 db.Project
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateProjectParams) (db.Project, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateProjectParams) db.Project); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.Project)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.CreateProjectParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Querier_CreateProject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateProject'
type Querier_CreateProject_Call struct {
	*mock.Call
}

// CreateProject is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.CreateProjectParams
func (_e *Querier_Expecter) CreateProject(ctx interface{}, arg interface{}) *Querier_CreateProject_Call {
	return &Querier_CreateProject_Call{Call: _e.mock.On("CreateProject", ctx, arg)}
}

func (_c *Querier_CreateProject_Call) Run(run func(ctx context.Context, arg db.CreateProjectParams)) *Querier_CreateProject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.CreateProjectParams))
	})
	return _c
}

func (_c *Querier_CreateProject_Call) Return(_a0 db.Project, _a1 error) *Querier_CreateProject_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Querier_CreateProject_Call) RunAndReturn(run func(context.Context, db.CreateProjectParams) (db.Project, error)) *Querier_CreateProject_Call {
	_c.Call.Return(run)
	return _c
}

// CreateProjectUpdate provides a mock function with given fields: ctx, arg
func (_m *Querier) CreateProjectUpdate(ctx context.Context, arg db.CreateProjectUpdateParams) (db.ProjectUpdate, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateProjectUpdate")
	}

	var r0 db.ProjectUpdate
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateProjectUpdateParams) (db.ProjectUpdate, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateProjectUpdateParams) db.ProjectUpdate); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.ProjectUpdate)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.CreateProjectUpdateParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Querier_CreateProjectUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateProjectUpdate'
type Querier_CreateProjectUpdate_Call struct {
	*mock.Call
}

// CreateProjectUpdate is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.CreateProjectUpdateParams
func (_e *Querier_Expecter) CreateProjectUpdate(ctx interface{}, arg interface{}) *Querier_CreateProjectUpdate_Call {
	return &Querier_CreateProjectUpdate_Call{Call: _e.mock.On("CreateProjectUpdate", ctx, arg)}
}

func (_c *Querier_CreateProjectUpdate_Call) Run(run func(ctx context.Context, arg db.CreateProjectUpdateParams)) *Querier_CreateProjectUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.CreateProjectUpdateParams))
	})
	return _c
}

func (_c *Querier_CreateProjectUpdate_Call) Return(_a0 db.ProjectUpdate, _a1 error) *Querier_CreateProjectUpdate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Querier_CreateProjectUpdate_Call) RunAndReturn(run func(context.Context, db.CreateProjectUpdateParams) (db.ProjectUpdate, error)) *Querier_CreateProjectUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// CreateSocialLoginUser provides a mock function with given fields: ctx, arg
func (_m *Querier) CreateSocialLoginUser(ctx context.Context, arg db.CreateSocialLoginUserParams) (db.User, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateSocialLoginUser")
	}

	var r0 db.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateSocialLoginUserParams) (db.User, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateSocialLoginUserParams) db.User); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.CreateSocialLoginUserParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Querier_CreateSocialLoginUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSocialLoginUser'
type Querier_CreateSocialLoginUser_Call struct {
	*mock.Call
}

// CreateSocialLoginUser is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.CreateSocialLoginUserParams
func (_e *Querier_Expecter) CreateSocialLoginUser(ctx interface{}, arg interface{}) *Querier_CreateSocialLoginUser_Call {
	return &Querier_CreateSocialLoginUser_Call{Call: _e.mock.On("CreateSocialLoginUser", ctx, arg)}
}

func (_c *Querier_CreateSocialLoginUser_Call) Run(run func(ctx context.Context, arg db.CreateSocialLoginUserParams)) *Querier_CreateSocialLoginUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.CreateSocialLoginUserParams))
	})
	return _c
}

func (_c *Querier_CreateSocialLoginUser_Call) Return(_a0 db.User, _a1 error) *Querier_CreateSocialLoginUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Querier_CreateSocialLoginUser_Call) RunAndReturn(run func(context.Context, db.CreateSocialLoginUserParams) (db.User, error)) *Querier_CreateSocialLoginUser_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUser provides a mock function with given fields: ctx, arg
func (_m *Querier) CreateUser(ctx context.Context, arg db.CreateUserParams) (db.User, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 db.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateUserParams) (db.User, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateUserParams) db.User); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.CreateUserParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Querier_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type Querier_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.CreateUserParams
func (_e *Querier_Expecter) CreateUser(ctx interface{}, arg interface{}) *Querier_CreateUser_Call {
	return &Querier_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, arg)}
}

func (_c *Querier_CreateUser_Call) Run(run func(ctx context.Context, arg db.CreateUserParams)) *Querier_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.CreateUserParams))
	})
	return _c
}

func (_c *Querier_CreateUser_Call) Return(_a0 db.User, _a1 error) *Querier_CreateUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Querier_CreateUser_Call) RunAndReturn(run func(context.Context, db.CreateUserParams) (db.User, error)) *Querier_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteProjectByID provides a mock function with given fields: ctx, id
func (_m *Querier) DeleteProjectByID(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteProjectByID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Querier_DeleteProjectByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteProjectByID'
type Querier_DeleteProjectByID_Call struct {
	*mock.Call
}

// DeleteProjectByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *Querier_Expecter) DeleteProjectByID(ctx interface{}, id interface{}) *Querier_DeleteProjectByID_Call {
	return &Querier_DeleteProjectByID_Call{Call: _e.mock.On("DeleteProjectByID", ctx, id)}
}

func (_c *Querier_DeleteProjectByID_Call) Run(run func(ctx context.Context, id int64)) *Querier_DeleteProjectByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *Querier_DeleteProjectByID_Call) Return(_a0 error) *Querier_DeleteProjectByID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Querier_DeleteProjectByID_Call) RunAndReturn(run func(context.Context, int64) error) *Querier_DeleteProjectByID_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteProjectUpdate provides a mock function with given fields: ctx, id
func (_m *Querier) DeleteProjectUpdate(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteProjectUpdate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Querier_DeleteProjectUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteProjectUpdate'
type Querier_DeleteProjectUpdate_Call struct {
	*mock.Call
}

// DeleteProjectUpdate is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *Querier_Expecter) DeleteProjectUpdate(ctx interface{}, id interface{}) *Querier_DeleteProjectUpdate_Call {
	return &Querier_DeleteProjectUpdate_Call{Call: _e.mock.On("DeleteProjectUpdate", ctx, id)}
}

func (_c *Querier_DeleteProjectUpdate_Call) Run(run func(ctx context.Context, id int64)) *Querier_DeleteProjectUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *Querier_DeleteProjectUpdate_Call) Return(_a0 error) *Querier_DeleteProjectUpdate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Querier_DeleteProjectUpdate_Call) RunAndReturn(run func(context.Context, int64) error) *Querier_DeleteProjectUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllCategories provides a mock function with given fields: ctx
func (_m *Querier) GetAllCategories(ctx context.Context) ([]db.Category, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllCategories")
	}

	var r0 []db.Category
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]db.Category, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []db.Category); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.Category)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Querier_GetAllCategories_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllCategories'
type Querier_GetAllCategories_Call struct {
	*mock.Call
}

// GetAllCategories is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Querier_Expecter) GetAllCategories(ctx interface{}) *Querier_GetAllCategories_Call {
	return &Querier_GetAllCategories_Call{Call: _e.mock.On("GetAllCategories", ctx)}
}

func (_c *Querier_GetAllCategories_Call) Run(run func(ctx context.Context)) *Querier_GetAllCategories_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Querier_GetAllCategories_Call) Return(_a0 []db.Category, _a1 error) *Querier_GetAllCategories_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Querier_GetAllCategories_Call) RunAndReturn(run func(context.Context) ([]db.Category, error)) *Querier_GetAllCategories_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllProjects provides a mock function with given fields: ctx, arg
func (_m *Querier) GetAllProjects(ctx context.Context, arg db.GetAllProjectsParams) ([]db.GetAllProjectsRow, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for GetAllProjects")
	}

	var r0 []db.GetAllProjectsRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.GetAllProjectsParams) ([]db.GetAllProjectsRow, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.GetAllProjectsParams) []db.GetAllProjectsRow); ok {
		r0 = rf(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.GetAllProjectsRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.GetAllProjectsParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Querier_GetAllProjects_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllProjects'
type Querier_GetAllProjects_Call struct {
	*mock.Call
}

// GetAllProjects is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.GetAllProjectsParams
func (_e *Querier_Expecter) GetAllProjects(ctx interface{}, arg interface{}) *Querier_GetAllProjects_Call {
	return &Querier_GetAllProjects_Call{Call: _e.mock.On("GetAllProjects", ctx, arg)}
}

func (_c *Querier_GetAllProjects_Call) Run(run func(ctx context.Context, arg db.GetAllProjectsParams)) *Querier_GetAllProjects_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.GetAllProjectsParams))
	})
	return _c
}

func (_c *Querier_GetAllProjects_Call) Return(_a0 []db.GetAllProjectsRow, _a1 error) *Querier_GetAllProjects_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Querier_GetAllProjects_Call) RunAndReturn(run func(context.Context, db.GetAllProjectsParams) ([]db.GetAllProjectsRow, error)) *Querier_GetAllProjects_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllUsers provides a mock function with given fields: ctx
func (_m *Querier) GetAllUsers(ctx context.Context) ([]db.GetAllUsersRow, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllUsers")
	}

	var r0 []db.GetAllUsersRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]db.GetAllUsersRow, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []db.GetAllUsersRow); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.GetAllUsersRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Querier_GetAllUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllUsers'
type Querier_GetAllUsers_Call struct {
	*mock.Call
}

// GetAllUsers is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Querier_Expecter) GetAllUsers(ctx interface{}) *Querier_GetAllUsers_Call {
	return &Querier_GetAllUsers_Call{Call: _e.mock.On("GetAllUsers", ctx)}
}

func (_c *Querier_GetAllUsers_Call) Run(run func(ctx context.Context)) *Querier_GetAllUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Querier_GetAllUsers_Call) Return(_a0 []db.GetAllUsersRow, _a1 error) *Querier_GetAllUsers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Querier_GetAllUsers_Call) RunAndReturn(run func(context.Context) ([]db.GetAllUsersRow, error)) *Querier_GetAllUsers_Call {
	_c.Call.Return(run)
	return _c
}

// GetBackingByID provides a mock function with given fields: ctx, id
func (_m *Querier) GetBackingByID(ctx context.Context, id int64) (db.Backing, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetBackingByID")
	}

	var r0 db.Backing
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (db.Backing, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) db.Backing); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(db.Backing)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Querier_GetBackingByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBackingByID'
type Querier_GetBackingByID_Call struct {
	*mock.Call
}

// GetBackingByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *Querier_Expecter) GetBackingByID(ctx interface{}, id interface{}) *Querier_GetBackingByID_Call {
	return &Querier_GetBackingByID_Call{Call: _e.mock.On("GetBackingByID", ctx, id)}
}

func (_c *Querier_GetBackingByID_Call) Run(run func(ctx context.Context, id int64)) *Querier_GetBackingByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *Querier_GetBackingByID_Call) Return(_a0 db.Backing, _a1 error) *Querier_GetBackingByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Querier_GetBackingByID_Call) RunAndReturn(run func(context.Context, int64) (db.Backing, error)) *Querier_GetBackingByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetBackingCountForProject provides a mock function with given fields: ctx, projectID
func (_m *Querier) GetBackingCountForProject(ctx context.Context, projectID int64) (int64, error) {
	ret := _m.Called(ctx, projectID)

	if len(ret) == 0 {
		panic("no return value specified for GetBackingCountForProject")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (int64, error)); ok {
		return rf(ctx, projectID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) int64); ok {
		r0 = rf(ctx, projectID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, projectID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Querier_GetBackingCountForProject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBackingCountForProject'
type Querier_GetBackingCountForProject_Call struct {
	*mock.Call
}

// GetBackingCountForProject is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID int64
func (_e *Querier_Expecter) GetBackingCountForProject(ctx interface{}, projectID interface{}) *Querier_GetBackingCountForProject_Call {
	return &Querier_GetBackingCountForProject_Call{Call: _e.mock.On("GetBackingCountForProject", ctx, projectID)}
}

func (_c *Querier_GetBackingCountForProject_Call) Run(run func(ctx context.Context, projectID int64)) *Querier_GetBackingCountForProject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *Querier_GetBackingCountForProject_Call) Return(_a0 int64, _a1 error) *Querier_GetBackingCountForProject_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Querier_GetBackingCountForProject_Call) RunAndReturn(run func(context.Context, int64) (int64, error)) *Querier_GetBackingCountForProject_Call {
	_c.Call.Return(run)
	return _c
}

// GetBackingsForProject provides a mock function with given fields: ctx, projectID
func (_m *Querier) GetBackingsForProject(ctx context.Context, projectID int64) ([]db.GetBackingsForProjectRow, error) {
	ret := _m.Called(ctx, projectID)

	if len(ret) == 0 {
		panic("no return value specified for GetBackingsForProject")
	}

	var r0 []db.GetBackingsForProjectRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]db.GetBackingsForProjectRow, error)); ok {
		return rf(ctx, projectID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []db.GetBackingsForProjectRow); ok {
		r0 = rf(ctx, projectID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.GetBackingsForProjectRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, projectID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Querier_GetBackingsForProject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBackingsForProject'
type Querier_GetBackingsForProject_Call struct {
	*mock.Call
}

// GetBackingsForProject is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID int64
func (_e *Querier_Expecter) GetBackingsForProject(ctx interface{}, projectID interface{}) *Querier_GetBackingsForProject_Call {
	return &Querier_GetBackingsForProject_Call{Call: _e.mock.On("GetBackingsForProject", ctx, projectID)}
}

func (_c *Querier_GetBackingsForProject_Call) Run(run func(ctx context.Context, projectID int64)) *Querier_GetBackingsForProject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *Querier_GetBackingsForProject_Call) Return(_a0 []db.GetBackingsForProjectRow, _a1 error) *Querier_GetBackingsForProject_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Querier_GetBackingsForProject_Call) RunAndReturn(run func(context.Context, int64) ([]db.GetBackingsForProjectRow, error)) *Querier_GetBackingsForProject_Call {
	_c.Call.Return(run)
	return _c
}

// GetBackingsForUser provides a mock function with given fields: ctx, userID
func (_m *Querier) GetBackingsForUser(ctx context.Context, userID *int64) ([]db.Backing, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetBackingsForUser")
	}

	var r0 []db.Backing
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *int64) ([]db.Backing, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *int64) []db.Backing); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.Backing)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Querier_GetBackingsForUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBackingsForUser'
type Querier_GetBackingsForUser_Call struct {
	*mock.Call
}

// GetBackingsForUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID *int64
func (_e *Querier_Expecter) GetBackingsForUser(ctx interface{}, userID interface{}) *Querier_GetBackingsForUser_Call {
	return &Querier_GetBackingsForUser_Call{Call: _e.mock.On("GetBackingsForUser", ctx, userID)}
}

func (_c *Querier_GetBackingsForUser_Call) Run(run func(ctx context.Context, userID *int64)) *Querier_GetBackingsForUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*int64))
	})
	return _c
}

func (_c *Querier_GetBackingsForUser_Call) Return(_a0 []db.Backing, _a1 error) *Querier_GetBackingsForUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Querier_GetBackingsForUser_Call) RunAndReturn(run func(context.Context, *int64) ([]db.Backing, error)) *Querier_GetBackingsForUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetEscrowUserByEmail provides a mock function with given fields: ctx, email
func (_m *Querier) GetEscrowUserByEmail(ctx context.Context, email string) (db.EscrowUser, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetEscrowUserByEmail")
	}

	var r0 db.EscrowUser
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (db.EscrowUser, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) db.EscrowUser); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Get(0).(db.EscrowUser)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Querier_GetEscrowUserByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEscrowUserByEmail'
type Querier_GetEscrowUserByEmail_Call struct {
	*mock.Call
}

// GetEscrowUserByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *Querier_Expecter) GetEscrowUserByEmail(ctx interface{}, email interface{}) *Querier_GetEscrowUserByEmail_Call {
	return &Querier_GetEscrowUserByEmail_Call{Call: _e.mock.On("GetEscrowUserByEmail", ctx, email)}
}

func (_c *Querier_GetEscrowUserByEmail_Call) Run(run func(ctx context.Context, email string)) *Querier_GetEscrowUserByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Querier_GetEscrowUserByEmail_Call) Return(_a0 db.EscrowUser, _a1 error) *Querier_GetEscrowUserByEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Querier_GetEscrowUserByEmail_Call) RunAndReturn(run func(context.Context, string) (db.EscrowUser, error)) *Querier_GetEscrowUserByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetEscrowUserByID provides a mock function with given fields: ctx, id
func (_m *Querier) GetEscrowUserByID(ctx context.Context, id int64) (db.EscrowUser, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetEscrowUserByID")
	}

	var r0 db.EscrowUser
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (db.EscrowUser, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) db.EscrowUser); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(db.EscrowUser)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Querier_GetEscrowUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEscrowUserByID'
type Querier_GetEscrowUserByID_Call struct {
	*mock.Call
}

// GetEscrowUserByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *Querier_Expecter) GetEscrowUserByID(ctx interface{}, id interface{}) *Querier_GetEscrowUserByID_Call {
	return &Querier_GetEscrowUserByID_Call{Call: _e.mock.On("GetEscrowUserByID", ctx, id)}
}

func (_c *Querier_GetEscrowUserByID_Call) Run(run func(ctx context.Context, id int64)) *Querier_GetEscrowUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *Querier_GetEscrowUserByID_Call) Return(_a0 db.EscrowUser, _a1 error) *Querier_GetEscrowUserByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Querier_GetEscrowUserByID_Call) RunAndReturn(run func(context.Context, int64) (db.EscrowUser, error)) *Querier_GetEscrowUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetFinishedProjects provides a mock function with given fields: ctx
func (_m *Querier) GetFinishedProjects(ctx context.Context) ([]db.GetFinishedProjectsRow, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetFinishedProjects")
	}

	var r0 []db.GetFinishedProjectsRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]db.GetFinishedProjectsRow, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []db.GetFinishedProjectsRow); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.GetFinishedProjectsRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Querier_GetFinishedProjects_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFinishedProjects'
type Querier_GetFinishedProjects_Call struct {
	*mock.Call
}

// GetFinishedProjects is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Querier_Expecter) GetFinishedProjects(ctx interface{}) *Querier_GetFinishedProjects_Call {
	return &Querier_GetFinishedProjects_Call{Call: _e.mock.On("GetFinishedProjects", ctx)}
}

func (_c *Querier_GetFinishedProjects_Call) Run(run func(ctx context.Context)) *Querier_GetFinishedProjects_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Querier_GetFinishedProjects_Call) Return(_a0 []db.GetFinishedProjectsRow, _a1 error) *Querier_GetFinishedProjects_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Querier_GetFinishedProjects_Call) RunAndReturn(run func(context.Context) ([]db.GetFinishedProjectsRow, error)) *Querier_GetFinishedProjects_Call {
	_c.Call.Return(run)
	return _c
}

// GetFirstBackingDonor provides a mock function with given fields: ctx, projectID
func (_m *Querier) GetFirstBackingDonor(ctx context.Context, projectID int64) (db.GetFirstBackingDonorRow, error) {
	ret := _m.Called(ctx, projectID)

	if len(ret) == 0 {
		panic("no return value specified for GetFirstBackingDonor")
	}

	var r0 db.GetFirstBackingDonorRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (db.GetFirstBackingDonorRow, error)); ok {
		return rf(ctx, projectID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) db.GetFirstBackingDonorRow); ok {
		r0 = rf(ctx, projectID)
	} else {
		r0 = ret.Get(0).(db.GetFirstBackingDonorRow)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, projectID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Querier_GetFirstBackingDonor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFirstBackingDonor'
type Querier_GetFirstBackingDonor_Call struct {
	*mock.Call
}

// GetFirstBackingDonor is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID int64
func (_e *Querier_Expecter) GetFirstBackingDonor(ctx interface{}, projectID interface{}) *Querier_GetFirstBackingDonor_Call {
	return &Querier_GetFirstBackingDonor_Call{Call: _e.mock.On("GetFirstBackingDonor", ctx, projectID)}
}

func (_c *Querier_GetFirstBackingDonor_Call) Run(run func(ctx context.Context, projectID int64)) *Querier_GetFirstBackingDonor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *Querier_GetFirstBackingDonor_Call) Return(_a0 db.GetFirstBackingDonorRow, _a1 error) *Querier_GetFirstBackingDonor_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Querier_GetFirstBackingDonor_Call) RunAndReturn(run func(context.Context, int64) (db.GetFirstBackingDonorRow, error)) *Querier_GetFirstBackingDonor_Call {
	_c.Call.Return(run)
	return _c
}

// GetMilestoneByID provides a mock function with given fields: ctx, id
func (_m *Querier) GetMilestoneByID(ctx context.Context, id int64) (db.GetMilestoneByIDRow, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetMilestoneByID")
	}

	var r0 db.GetMilestoneByIDRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (db.GetMilestoneByIDRow, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) db.GetMilestoneByIDRow); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(db.GetMilestoneByIDRow)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Querier_GetMilestoneByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMilestoneByID'
type Querier_GetMilestoneByID_Call struct {
	*mock.Call
}

// GetMilestoneByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *Querier_Expecter) GetMilestoneByID(ctx interface{}, id interface{}) *Querier_GetMilestoneByID_Call {
	return &Querier_GetMilestoneByID_Call{Call: _e.mock.On("GetMilestoneByID", ctx, id)}
}

func (_c *Querier_GetMilestoneByID_Call) Run(run func(ctx context.Context, id int64)) *Querier_GetMilestoneByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *Querier_GetMilestoneByID_Call) Return(_a0 db.GetMilestoneByIDRow, _a1 error) *Querier_GetMilestoneByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Querier_GetMilestoneByID_Call) RunAndReturn(run func(context.Context, int64) (db.GetMilestoneByIDRow, error)) *Querier_GetMilestoneByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetMilestoneForProject provides a mock function with given fields: ctx, projectID
func (_m *Querier) GetMilestoneForProject(ctx context.Context, projectID int64) ([]db.GetMilestoneForProjectRow, error) {
	ret := _m.Called(ctx, projectID)

	if len(ret) == 0 {
		panic("no return value specified for GetMilestoneForProject")
	}

	var r0 []db.GetMilestoneForProjectRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]db.GetMilestoneForProjectRow, error)); ok {
		return rf(ctx, projectID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []db.GetMilestoneForProjectRow); ok {
		r0 = rf(ctx, projectID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.GetMilestoneForProjectRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, projectID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Querier_GetMilestoneForProject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMilestoneForProject'
type Querier_GetMilestoneForProject_Call struct {
	*mock.Call
}

// GetMilestoneForProject is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID int64
func (_e *Querier_Expecter) GetMilestoneForProject(ctx interface{}, projectID interface{}) *Querier_GetMilestoneForProject_Call {
	return &Querier_GetMilestoneForProject_Call{Call: _e.mock.On("GetMilestoneForProject", ctx, projectID)}
}

func (_c *Querier_GetMilestoneForProject_Call) Run(run func(ctx context.Context, projectID int64)) *Querier_GetMilestoneForProject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *Querier_GetMilestoneForProject_Call) Return(_a0 []db.GetMilestoneForProjectRow, _a1 error) *Querier_GetMilestoneForProject_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Querier_GetMilestoneForProject_Call) RunAndReturn(run func(context.Context, int64) ([]db.GetMilestoneForProjectRow, error)) *Querier_GetMilestoneForProject_Call {
	_c.Call.Return(run)
	return _c
}

// GetMostBackingDonor provides a mock function with given fields: ctx, projectID
func (_m *Querier) GetMostBackingDonor(ctx context.Context, projectID int64) (db.GetMostBackingDonorRow, error) {
	ret := _m.Called(ctx, projectID)

	if len(ret) == 0 {
		panic("no return value specified for GetMostBackingDonor")
	}

	var r0 db.GetMostBackingDonorRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (db.GetMostBackingDonorRow, error)); ok {
		return rf(ctx, projectID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) db.GetMostBackingDonorRow); ok {
		r0 = rf(ctx, projectID)
	} else {
		r0 = ret.Get(0).(db.GetMostBackingDonorRow)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, projectID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Querier_GetMostBackingDonor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMostBackingDonor'
type Querier_GetMostBackingDonor_Call struct {
	*mock.Call
}

// GetMostBackingDonor is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID int64
func (_e *Querier_Expecter) GetMostBackingDonor(ctx interface{}, projectID interface{}) *Querier_GetMostBackingDonor_Call {
	return &Querier_GetMostBackingDonor_Call{Call: _e.mock.On("GetMostBackingDonor", ctx, projectID)}
}

func (_c *Querier_GetMostBackingDonor_Call) Run(run func(ctx context.Context, projectID int64)) *Querier_GetMostBackingDonor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *Querier_GetMostBackingDonor_Call) Return(_a0 db.GetMostBackingDonorRow, _a1 error) *Querier_GetMostBackingDonor_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Querier_GetMostBackingDonor_Call) RunAndReturn(run func(context.Context, int64) (db.GetMostBackingDonorRow, error)) *Querier_GetMostBackingDonor_Call {
	_c.Call.Return(run)
	return _c
}

// GetMostRecentBackingDonor provides a mock function with given fields: ctx, projectID
func (_m *Querier) GetMostRecentBackingDonor(ctx context.Context, projectID int64) (db.GetMostRecentBackingDonorRow, error) {
	ret := _m.Called(ctx, projectID)

	if len(ret) == 0 {
		panic("no return value specified for GetMostRecentBackingDonor")
	}

	var r0 db.GetMostRecentBackingDonorRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (db.GetMostRecentBackingDonorRow, error)); ok {
		return rf(ctx, projectID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) db.GetMostRecentBackingDonorRow); ok {
		r0 = rf(ctx, projectID)
	} else {
		r0 = ret.Get(0).(db.GetMostRecentBackingDonorRow)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, projectID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Querier_GetMostRecentBackingDonor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMostRecentBackingDonor'
type Querier_GetMostRecentBackingDonor_Call struct {
	*mock.Call
}

// GetMostRecentBackingDonor is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID int64
func (_e *Querier_Expecter) GetMostRecentBackingDonor(ctx interface{}, projectID interface{}) *Querier_GetMostRecentBackingDonor_Call {
	return &Querier_GetMostRecentBackingDonor_Call{Call: _e.mock.On("GetMostRecentBackingDonor", ctx, projectID)}
}

func (_c *Querier_GetMostRecentBackingDonor_Call) Run(run func(ctx context.Context, projectID int64)) *Querier_GetMostRecentBackingDonor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *Querier_GetMostRecentBackingDonor_Call) Return(_a0 db.GetMostRecentBackingDonorRow, _a1 error) *Querier_GetMostRecentBackingDonor_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Querier_GetMostRecentBackingDonor_Call) RunAndReturn(run func(context.Context, int64) (db.GetMostRecentBackingDonorRow, error)) *Querier_GetMostRecentBackingDonor_Call {
	_c.Call.Return(run)
	return _c
}

// GetPendingProjects provides a mock function with given fields: ctx
func (_m *Querier) GetPendingProjects(ctx context.Context) ([]db.GetPendingProjectsRow, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetPendingProjects")
	}

	var r0 []db.GetPendingProjectsRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]db.GetPendingProjectsRow, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []db.GetPendingProjectsRow); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.GetPendingProjectsRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Querier_GetPendingProjects_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPendingProjects'
type Querier_GetPendingProjects_Call struct {
	*mock.Call
}

// GetPendingProjects is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Querier_Expecter) GetPendingProjects(ctx interface{}) *Querier_GetPendingProjects_Call {
	return &Querier_GetPendingProjects_Call{Call: _e.mock.On("GetPendingProjects", ctx)}
}

func (_c *Querier_GetPendingProjects_Call) Run(run func(ctx context.Context)) *Querier_GetPendingProjects_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Querier_GetPendingProjects_Call) Return(_a0 []db.GetPendingProjectsRow, _a1 error) *Querier_GetPendingProjects_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Querier_GetPendingProjects_Call) RunAndReturn(run func(context.Context) ([]db.GetPendingProjectsRow, error)) *Querier_GetPendingProjects_Call {
	_c.Call.Return(run)
	return _c
}

// GetPendingVerificationUsers provides a mock function with given fields: ctx
func (_m *Querier) GetPendingVerificationUsers(ctx context.Context) ([]db.GetPendingVerificationUsersRow, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetPendingVerificationUsers")
	}

	var r0 []db.GetPendingVerificationUsersRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]db.GetPendingVerificationUsersRow, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []db.GetPendingVerificationUsersRow); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.GetPendingVerificationUsersRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Querier_GetPendingVerificationUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPendingVerificationUsers'
type Querier_GetPendingVerificationUsers_Call struct {
	*mock.Call
}

// GetPendingVerificationUsers is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Querier_Expecter) GetPendingVerificationUsers(ctx interface{}) *Querier_GetPendingVerificationUsers_Call {
	return &Querier_GetPendingVerificationUsers_Call{Call: _e.mock.On("GetPendingVerificationUsers", ctx)}
}

func (_c *Querier_GetPendingVerificationUsers_Call) Run(run func(ctx context.Context)) *Querier_GetPendingVerificationUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Querier_GetPendingVerificationUsers_Call) Return(_a0 []db.GetPendingVerificationUsersRow, _a1 error) *Querier_GetPendingVerificationUsers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Querier_GetPendingVerificationUsers_Call) RunAndReturn(run func(context.Context) ([]db.GetPendingVerificationUsersRow, error)) *Querier_GetPendingVerificationUsers_Call {
	_c.Call.Return(run)
	return _c
}

// GetProjectByID provides a mock function with given fields: ctx, id
func (_m *Querier) GetProjectByID(ctx context.Context, id int64) (db.GetProjectByIDRow, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetProjectByID")
	}

	var r0 db.GetProjectByIDRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (db.GetProjectByIDRow, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) db.GetProjectByIDRow); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(db.GetProjectByIDRow)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Querier_GetProjectByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProjectByID'
type Querier_GetProjectByID_Call struct {
	*mock.Call
}

// GetProjectByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *Querier_Expecter) GetProjectByID(ctx interface{}, id interface{}) *Querier_GetProjectByID_Call {
	return &Querier_GetProjectByID_Call{Call: _e.mock.On("GetProjectByID", ctx, id)}
}

func (_c *Querier_GetProjectByID_Call) Run(run func(ctx context.Context, id int64)) *Querier_GetProjectByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *Querier_GetProjectByID_Call) Return(_a0 db.GetProjectByIDRow, _a1 error) *Querier_GetProjectByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Querier_GetProjectByID_Call) RunAndReturn(run func(context.Context, int64) (db.GetProjectByIDRow, error)) *Querier_GetProjectByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetProjectUpdates provides a mock function with given fields: ctx, projectID
func (_m *Querier) GetProjectUpdates(ctx context.Context, projectID int64) ([]db.ProjectUpdate, error) {
	ret := _m.Called(ctx, projectID)

	if len(ret) == 0 {
		panic("no return value specified for GetProjectUpdates")
	}

	var r0 []db.ProjectUpdate
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]db.ProjectUpdate, error)); ok {
		return rf(ctx, projectID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []db.ProjectUpdate); ok {
		r0 = rf(ctx, projectID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.ProjectUpdate)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, projectID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Querier_GetProjectUpdates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProjectUpdates'
type Querier_GetProjectUpdates_Call struct {
	*mock.Call
}

// GetProjectUpdates is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID int64
func (_e *Querier_Expecter) GetProjectUpdates(ctx interface{}, projectID interface{}) *Querier_GetProjectUpdates_Call {
	return &Querier_GetProjectUpdates_Call{Call: _e.mock.On("GetProjectUpdates", ctx, projectID)}
}

func (_c *Querier_GetProjectUpdates_Call) Run(run func(ctx context.Context, projectID int64)) *Querier_GetProjectUpdates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *Querier_GetProjectUpdates_Call) Return(_a0 []db.ProjectUpdate, _a1 error) *Querier_GetProjectUpdates_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Querier_GetProjectUpdates_Call) RunAndReturn(run func(context.Context, int64) ([]db.ProjectUpdate, error)) *Querier_GetProjectUpdates_Call {
	_c.Call.Return(run)
	return _c
}

// GetProjectsForUser provides a mock function with given fields: ctx, userID
func (_m *Querier) GetProjectsForUser(ctx context.Context, userID int64) ([]db.GetProjectsForUserRow, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetProjectsForUser")
	}

	var r0 []db.GetProjectsForUserRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]db.GetProjectsForUserRow, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []db.GetProjectsForUserRow); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.GetProjectsForUserRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Querier_GetProjectsForUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProjectsForUser'
type Querier_GetProjectsForUser_Call struct {
	*mock.Call
}

// GetProjectsForUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *Querier_Expecter) GetProjectsForUser(ctx interface{}, userID interface{}) *Querier_GetProjectsForUser_Call {
	return &Querier_GetProjectsForUser_Call{Call: _e.mock.On("GetProjectsForUser", ctx, userID)}
}

func (_c *Querier_GetProjectsForUser_Call) Run(run func(ctx context.Context, userID int64)) *Querier_GetProjectsForUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *Querier_GetProjectsForUser_Call) Return(_a0 []db.GetProjectsForUserRow, _a1 error) *Querier_GetProjectsForUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Querier_GetProjectsForUser_Call) RunAndReturn(run func(context.Context, int64) ([]db.GetProjectsForUserRow, error)) *Querier_GetProjectsForUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUnresolvedMilestones provides a mock function with given fields: ctx
func (_m *Querier) GetUnresolvedMilestones(ctx context.Context) ([]db.GetUnresolvedMilestonesRow, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetUnresolvedMilestones")
	}

	var r0 []db.GetUnresolvedMilestonesRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]db.GetUnresolvedMilestonesRow, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []db.GetUnresolvedMilestonesRow); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.GetUnresolvedMilestonesRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Querier_GetUnresolvedMilestones_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUnresolvedMilestones'
type Querier_GetUnresolvedMilestones_Call struct {
	*mock.Call
}

// GetUnresolvedMilestones is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Querier_Expecter) GetUnresolvedMilestones(ctx interface{}) *Querier_GetUnresolvedMilestones_Call {
	return &Querier_GetUnresolvedMilestones_Call{Call: _e.mock.On("GetUnresolvedMilestones", ctx)}
}

func (_c *Querier_GetUnresolvedMilestones_Call) Run(run func(ctx context.Context)) *Querier_GetUnresolvedMilestones_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Querier_GetUnresolvedMilestones_Call) Return(_a0 []db.GetUnresolvedMilestonesRow, _a1 error) *Querier_GetUnresolvedMilestones_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Querier_GetUnresolvedMilestones_Call) RunAndReturn(run func(context.Context) ([]db.GetUnresolvedMilestonesRow, error)) *Querier_GetUnresolvedMilestones_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByEmail provides a mock function with given fields: ctx, email
func (_m *Querier) GetUserByEmail(ctx context.Context, email string) (db.User, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByEmail")
	}

	var r0 db.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (db.User, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) db.User); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Get(0).(db.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Querier_GetUserByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByEmail'
type Querier_GetUserByEmail_Call struct {
	*mock.Call
}

// GetUserByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *Querier_Expecter) GetUserByEmail(ctx interface{}, email interface{}) *Querier_GetUserByEmail_Call {
	return &Querier_GetUserByEmail_Call{Call: _e.mock.On("GetUserByEmail", ctx, email)}
}

func (_c *Querier_GetUserByEmail_Call) Run(run func(ctx context.Context, email string)) *Querier_GetUserByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Querier_GetUserByEmail_Call) Return(_a0 db.User, _a1 error) *Querier_GetUserByEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Querier_GetUserByEmail_Call) RunAndReturn(run func(context.Context, string) (db.User, error)) *Querier_GetUserByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByID provides a mock function with given fields: ctx, id
func (_m *Querier) GetUserByID(ctx context.Context, id int64) (db.User, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 db.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (db.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) db.User); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(db.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Querier_GetUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByID'
type Querier_GetUserByID_Call struct {
	*mock.Call
}

// GetUserByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *Querier_Expecter) GetUserByID(ctx interface{}, id interface{}) *Querier_GetUserByID_Call {
	return &Querier_GetUserByID_Call{Call: _e.mock.On("GetUserByID", ctx, id)}
}

func (_c *Querier_GetUserByID_Call) Run(run func(ctx context.Context, id int64)) *Querier_GetUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *Querier_GetUserByID_Call) Return(_a0 db.User, _a1 error) *Querier_GetUserByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Querier_GetUserByID_Call) RunAndReturn(run func(context.Context, int64) (db.User, error)) *Querier_GetUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// SearchProjects provides a mock function with given fields: ctx, arg
func (_m *Querier) SearchProjects(ctx context.Context, arg db.SearchProjectsParams) ([]db.SearchProjectsRow, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for SearchProjects")
	}

	var r0 []db.SearchProjectsRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.SearchProjectsParams) ([]db.SearchProjectsRow, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.SearchProjectsParams) []db.SearchProjectsRow); ok {
		r0 = rf(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.SearchProjectsRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.SearchProjectsParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Querier_SearchProjects_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchProjects'
type Querier_SearchProjects_Call struct {
	*mock.Call
}

// SearchProjects is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.SearchProjectsParams
func (_e *Querier_Expecter) SearchProjects(ctx interface{}, arg interface{}) *Querier_SearchProjects_Call {
	return &Querier_SearchProjects_Call{Call: _e.mock.On("SearchProjects", ctx, arg)}
}

func (_c *Querier_SearchProjects_Call) Run(run func(ctx context.Context, arg db.SearchProjectsParams)) *Querier_SearchProjects_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.SearchProjectsParams))
	})
	return _c
}

func (_c *Querier_SearchProjects_Call) Return(_a0 []db.SearchProjectsRow, _a1 error) *Querier_SearchProjects_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Querier_SearchProjects_Call) RunAndReturn(run func(context.Context, db.SearchProjectsParams) ([]db.SearchProjectsRow, error)) *Querier_SearchProjects_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateEscrowUserByID provides a mock function with given fields: ctx, arg
func (_m *Querier) UpdateEscrowUserByID(ctx context.Context, arg db.UpdateEscrowUserByIDParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateEscrowUserByID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, db.UpdateEscrowUserByIDParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Querier_UpdateEscrowUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateEscrowUserByID'
type Querier_UpdateEscrowUserByID_Call struct {
	*mock.Call
}

// UpdateEscrowUserByID is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.UpdateEscrowUserByIDParams
func (_e *Querier_Expecter) UpdateEscrowUserByID(ctx interface{}, arg interface{}) *Querier_UpdateEscrowUserByID_Call {
	return &Querier_UpdateEscrowUserByID_Call{Call: _e.mock.On("UpdateEscrowUserByID", ctx, arg)}
}

func (_c *Querier_UpdateEscrowUserByID_Call) Run(run func(ctx context.Context, arg db.UpdateEscrowUserByIDParams)) *Querier_UpdateEscrowUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.UpdateEscrowUserByIDParams))
	})
	return _c
}

func (_c *Querier_UpdateEscrowUserByID_Call) Return(_a0 error) *Querier_UpdateEscrowUserByID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Querier_UpdateEscrowUserByID_Call) RunAndReturn(run func(context.Context, db.UpdateEscrowUserByIDParams) error) *Querier_UpdateEscrowUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateMilestoneFund provides a mock function with given fields: ctx, arg
func (_m *Querier) UpdateMilestoneFund(ctx context.Context, arg db.UpdateMilestoneFundParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMilestoneFund")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, db.UpdateMilestoneFundParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Querier_UpdateMilestoneFund_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateMilestoneFund'
type Querier_UpdateMilestoneFund_Call struct {
	*mock.Call
}

// UpdateMilestoneFund is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.UpdateMilestoneFundParams
func (_e *Querier_Expecter) UpdateMilestoneFund(ctx interface{}, arg interface{}) *Querier_UpdateMilestoneFund_Call {
	return &Querier_UpdateMilestoneFund_Call{Call: _e.mock.On("UpdateMilestoneFund", ctx, arg)}
}

func (_c *Querier_UpdateMilestoneFund_Call) Run(run func(ctx context.Context, arg db.UpdateMilestoneFundParams)) *Querier_UpdateMilestoneFund_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.UpdateMilestoneFundParams))
	})
	return _c
}

func (_c *Querier_UpdateMilestoneFund_Call) Return(_a0 error) *Querier_UpdateMilestoneFund_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Querier_UpdateMilestoneFund_Call) RunAndReturn(run func(context.Context, db.UpdateMilestoneFundParams) error) *Querier_UpdateMilestoneFund_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateMilestoneStatus provides a mock function with given fields: ctx, id
func (_m *Querier) UpdateMilestoneStatus(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMilestoneStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Querier_UpdateMilestoneStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateMilestoneStatus'
type Querier_UpdateMilestoneStatus_Call struct {
	*mock.Call
}

// UpdateMilestoneStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *Querier_Expecter) UpdateMilestoneStatus(ctx interface{}, id interface{}) *Querier_UpdateMilestoneStatus_Call {
	return &Querier_UpdateMilestoneStatus_Call{Call: _e.mock.On("UpdateMilestoneStatus", ctx, id)}
}

func (_c *Querier_UpdateMilestoneStatus_Call) Run(run func(ctx context.Context, id int64)) *Querier_UpdateMilestoneStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *Querier_UpdateMilestoneStatus_Call) Return(_a0 error) *Querier_UpdateMilestoneStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Querier_UpdateMilestoneStatus_Call) RunAndReturn(run func(context.Context, int64) error) *Querier_UpdateMilestoneStatus_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateProjectByID provides a mock function with given fields: ctx, arg
func (_m *Querier) UpdateProjectByID(ctx context.Context, arg db.UpdateProjectByIDParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProjectByID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, db.UpdateProjectByIDParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Querier_UpdateProjectByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProjectByID'
type Querier_UpdateProjectByID_Call struct {
	*mock.Call
}

// UpdateProjectByID is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.UpdateProjectByIDParams
func (_e *Querier_Expecter) UpdateProjectByID(ctx interface{}, arg interface{}) *Querier_UpdateProjectByID_Call {
	return &Querier_UpdateProjectByID_Call{Call: _e.mock.On("UpdateProjectByID", ctx, arg)}
}

func (_c *Querier_UpdateProjectByID_Call) Run(run func(ctx context.Context, arg db.UpdateProjectByIDParams)) *Querier_UpdateProjectByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.UpdateProjectByIDParams))
	})
	return _c
}

func (_c *Querier_UpdateProjectByID_Call) Return(_a0 error) *Querier_UpdateProjectByID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Querier_UpdateProjectByID_Call) RunAndReturn(run func(context.Context, db.UpdateProjectByIDParams) error) *Querier_UpdateProjectByID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateProjectStatus provides a mock function with given fields: ctx, arg
func (_m *Querier) UpdateProjectStatus(ctx context.Context, arg db.UpdateProjectStatusParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProjectStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, db.UpdateProjectStatusParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Querier_UpdateProjectStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProjectStatus'
type Querier_UpdateProjectStatus_Call struct {
	*mock.Call
}

// UpdateProjectStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.UpdateProjectStatusParams
func (_e *Querier_Expecter) UpdateProjectStatus(ctx interface{}, arg interface{}) *Querier_UpdateProjectStatus_Call {
	return &Querier_UpdateProjectStatus_Call{Call: _e.mock.On("UpdateProjectStatus", ctx, arg)}
}

func (_c *Querier_UpdateProjectStatus_Call) Run(run func(ctx context.Context, arg db.UpdateProjectStatusParams)) *Querier_UpdateProjectStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.UpdateProjectStatusParams))
	})
	return _c
}

func (_c *Querier_UpdateProjectStatus_Call) Return(_a0 error) *Querier_UpdateProjectStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Querier_UpdateProjectStatus_Call) RunAndReturn(run func(context.Context, db.UpdateProjectStatusParams) error) *Querier_UpdateProjectStatus_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUserByID provides a mock function with given fields: ctx, arg
func (_m *Querier) UpdateUserByID(ctx context.Context, arg db.UpdateUserByIDParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserByID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, db.UpdateUserByIDParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Querier_UpdateUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUserByID'
type Querier_UpdateUserByID_Call struct {
	*mock.Call
}

// UpdateUserByID is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.UpdateUserByIDParams
func (_e *Querier_Expecter) UpdateUserByID(ctx interface{}, arg interface{}) *Querier_UpdateUserByID_Call {
	return &Querier_UpdateUserByID_Call{Call: _e.mock.On("UpdateUserByID", ctx, arg)}
}

func (_c *Querier_UpdateUserByID_Call) Run(run func(ctx context.Context, arg db.UpdateUserByIDParams)) *Querier_UpdateUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.UpdateUserByIDParams))
	})
	return _c
}

func (_c *Querier_UpdateUserByID_Call) Return(_a0 error) *Querier_UpdateUserByID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Querier_UpdateUserByID_Call) RunAndReturn(run func(context.Context, db.UpdateUserByIDParams) error) *Querier_UpdateUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUserPassword provides a mock function with given fields: ctx, arg
func (_m *Querier) UpdateUserPassword(ctx context.Context, arg db.UpdateUserPasswordParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserPassword")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, db.UpdateUserPasswordParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Querier_UpdateUserPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUserPassword'
type Querier_UpdateUserPassword_Call struct {
	*mock.Call
}

// UpdateUserPassword is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.UpdateUserPasswordParams
func (_e *Querier_Expecter) UpdateUserPassword(ctx interface{}, arg interface{}) *Querier_UpdateUserPassword_Call {
	return &Querier_UpdateUserPassword_Call{Call: _e.mock.On("UpdateUserPassword", ctx, arg)}
}

func (_c *Querier_UpdateUserPassword_Call) Run(run func(ctx context.Context, arg db.UpdateUserPasswordParams)) *Querier_UpdateUserPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.UpdateUserPasswordParams))
	})
	return _c
}

func (_c *Querier_UpdateUserPassword_Call) Return(_a0 error) *Querier_UpdateUserPassword_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Querier_UpdateUserPassword_Call) RunAndReturn(run func(context.Context, db.UpdateUserPasswordParams) error) *Querier_UpdateUserPassword_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateVerificationStatus provides a mock function with given fields: ctx, arg
func (_m *Querier) UpdateVerificationStatus(ctx context.Context, arg db.UpdateVerificationStatusParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateVerificationStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, db.UpdateVerificationStatusParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Querier_UpdateVerificationStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateVerificationStatus'
type Querier_UpdateVerificationStatus_Call struct {
	*mock.Call
}

// UpdateVerificationStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.UpdateVerificationStatusParams
func (_e *Querier_Expecter) UpdateVerificationStatus(ctx interface{}, arg interface{}) *Querier_UpdateVerificationStatus_Call {
	return &Querier_UpdateVerificationStatus_Call{Call: _e.mock.On("UpdateVerificationStatus", ctx, arg)}
}

func (_c *Querier_UpdateVerificationStatus_Call) Run(run func(ctx context.Context, arg db.UpdateVerificationStatusParams)) *Querier_UpdateVerificationStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.UpdateVerificationStatusParams))
	})
	return _c
}

func (_c *Querier_UpdateVerificationStatus_Call) Return(_a0 error) *Querier_UpdateVerificationStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Querier_UpdateVerificationStatus_Call) RunAndReturn(run func(context.Context, db.UpdateVerificationStatusParams) error) *Querier_UpdateVerificationStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewQuerier creates a new instance of Querier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewQuerier(t interface {
	mock.TestingT
	Cleanup(func())
}) *Querier {
	mock := &Querier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
