// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ProjectStatus string

const (
	ProjectStatusPending  ProjectStatus = "pending"
	ProjectStatusOngoing  ProjectStatus = "ongoing"
	ProjectStatusRejected ProjectStatus = "rejected"
	ProjectStatusFinished ProjectStatus = "finished"
)

func (e *ProjectStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProjectStatus(s)
	case string:
		*e = ProjectStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ProjectStatus: %T", src)
	}
	return nil
}

type NullProjectStatus struct {
	ProjectStatus ProjectStatus
	Valid         bool // Valid is true if ProjectStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProjectStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ProjectStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProjectStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProjectStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProjectStatus), nil
}

type Backing struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	ProjectID     uuid.UUID
	Amount        int64
	WordOfSupport *string
	CreatedAt     time.Time
}

type Category struct {
	ID           int32
	Name         string
	Description  string
	CoverPicture string
}

type Certificate struct {
	ID           uuid.UUID
	EscrowUserID uuid.UUID
	UserID       uuid.UUID
	MilestoneID  uuid.UUID
	Verified     *bool
	VerifiedAt   pgtype.Timestamptz
	CreatedAt    time.Time
}

type EscrowUser struct {
	ID             uuid.UUID
	Email          string
	HashedPassword string
	CreatedAt      time.Time
}

type Milestone struct {
	ID              uuid.UUID
	ProjectID       uuid.UUID
	Title           string
	Description     *string
	FundGoal        int64
	CurrentFund     int64
	BankDescription string
	Completed       bool
}

type Project struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	Title          string
	Description    string
	CoverPicture   string
	CategoryID     int32
	StartDate      time.Time
	EndDate        time.Time
	ReceiverNumber string
	ReceiverName   string
	Address        string
	District       string
	City           string
	Country        string
	Status         NullProjectStatus
}

type ProjectUpdate struct {
	ID              uuid.UUID
	ProjectID       uuid.UUID
	AttachmentPhoto *string
	Description     string
	CreatedAt       time.Time
}

type User struct {
	ID             uuid.UUID
	Email          string
	FirstName      string
	LastName       string
	ProfilePicture *string
	HashedPassword string
	Activated      bool
	CreatedAt      time.Time
}
