// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type UserType string

const (
	UserTypeRegular UserType = "regular"
	UserTypeEscrow  UserType = "escrow"
)

func (e *UserType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserType(s)
	case string:
		*e = UserType(s)
	default:
		return fmt.Errorf("unsupported scan type for UserType: %T", src)
	}
	return nil
}

type NullUserType struct {
	UserType UserType
	Valid    bool // Valid is true if UserType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserType) Scan(value interface{}) error {
	if value == nil {
		ns.UserType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserType), nil
}

type Backing struct {
	ID          pgtype.UUID
	ProjectID   pgtype.UUID
	BackerID    pgtype.UUID
	Amount      pgtype.Numeric
	BackingDate pgtype.Timestamptz
}

type Project struct {
	ID            pgtype.UUID
	UserID        pgtype.UUID
	Title         string
	Description   string
	CoverPicture  string
	GoalAmount    pgtype.Numeric
	CurrentAmount pgtype.Numeric
	Country       string
	Province      string
	StartDate     pgtype.Timestamptz
	EndDate       pgtype.Timestamptz
	IsActive      bool
}

type ProjectComment struct {
	ID              pgtype.UUID
	ProjectID       pgtype.UUID
	BackerID        pgtype.UUID
	ParentCommentID pgtype.UUID
	Content         string
	CommentedAt     pgtype.Timestamptz
}

type ProjectUpdate struct {
	ID          pgtype.UUID
	ProjectID   pgtype.UUID
	Description string
	UpdateDate  pgtype.Timestamptz
}

type User struct {
	ID             pgtype.UUID
	Username       string
	HashedPassword string
	Email          string
	FirstName      pgtype.Text
	LastName       pgtype.Text
	ProfilePicture pgtype.Text
	Activated      bool
	UserType       UserType
}
