// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	ActivateUser(ctx context.Context, id uuid.UUID) error
	CreateBacking(ctx context.Context, arg CreateBackingParams) (Backing, error)
	CreateCard(ctx context.Context, arg CreateCardParams) (Card, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	CreateProjectUpdate(ctx context.Context, arg CreateProjectUpdateParams) (ProjectUpdate, error)
	CreateReport(ctx context.Context, arg CreateReportParams) (Report, error)
	CreateSocialLoginUser(ctx context.Context, arg CreateSocialLoginUserParams) (User, error)
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteProjectByID(ctx context.Context, id uuid.UUID) error
	DeleteProjectUpdate(ctx context.Context, id uuid.UUID) error
	GetAllCategories(ctx context.Context) ([]Category, error)
	GetAllProjects(ctx context.Context, arg GetAllProjectsParams) ([]GetAllProjectsRow, error)
	GetAllTransactions(ctx context.Context) ([]Transaction, error)
	GetAllUsers(ctx context.Context) ([]GetAllUsersRow, error)
	GetBackingByID(ctx context.Context, id uuid.UUID) (Backing, error)
	GetBackingCountForProject(ctx context.Context, projectID uuid.UUID) (int64, error)
	GetBackingTransactionsForProject(ctx context.Context, projectID uuid.UUID) ([]Transaction, error)
	GetBackingsForProject(ctx context.Context, projectID uuid.UUID) ([]GetBackingsForProjectRow, error)
	GetBackingsForUser(ctx context.Context, backerID uuid.UUID) ([]Backing, error)
	GetCardByID(ctx context.Context, id uuid.UUID) (Card, error)
	GetEndedProjects(ctx context.Context) ([]GetEndedProjectsRow, error)
	GetEscrowUser(ctx context.Context) (EscrowUser, error)
	GetEscrowUserByEmail(ctx context.Context, email string) (EscrowUser, error)
	GetEscrowUserByID(ctx context.Context, id uuid.UUID) (EscrowUser, error)
	GetFirstBackingDonor(ctx context.Context, projectID uuid.UUID) (GetFirstBackingDonorRow, error)
	GetMostBackingDonor(ctx context.Context, projectID uuid.UUID) (GetMostBackingDonorRow, error)
	GetMostRecentBackingDonor(ctx context.Context, projectID uuid.UUID) (GetMostRecentBackingDonorRow, error)
	GetProjectByID(ctx context.Context, id uuid.UUID) (Project, error)
	GetProjectUpdates(ctx context.Context, projectID uuid.UUID) ([]ProjectUpdate, error)
	GetProjectsForUser(ctx context.Context, userID uuid.UUID) ([]Project, error)
	GetStatistics(ctx context.Context) (GetStatisticsRow, error)
	GetTransactionByID(ctx context.Context, id uuid.UUID) (Transaction, error)
	GetTransactionsForProject(ctx context.Context, projectID uuid.UUID) ([]Transaction, error)
	GetTransactionsStatsByWeek(ctx context.Context) ([]GetTransactionsStatsByWeekRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	SearchProjects(ctx context.Context, arg SearchProjectsParams) ([]SearchProjectsRow, error)
	UpdateEscrowCard(ctx context.Context, arg UpdateEscrowCardParams) error
	UpdateEscrowUserByID(ctx context.Context, arg UpdateEscrowUserByIDParams) error
	UpdateFinishedProjectsStatus(ctx context.Context) ([]Project, error)
	UpdateProjectBackingStatus(ctx context.Context, arg UpdateProjectBackingStatusParams) error
	UpdateProjectByID(ctx context.Context, arg UpdateProjectByIDParams) error
	UpdateProjectCard(ctx context.Context, arg UpdateProjectCardParams) error
	UpdateProjectFund(ctx context.Context, arg UpdateProjectFundParams) error
	UpdateProjectStatus(ctx context.Context, arg UpdateProjectStatusParams) error
	UpdateTransactionStatus(ctx context.Context, arg UpdateTransactionStatusParams) error
	UpdateUserByID(ctx context.Context, arg UpdateUserByIDParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
}

var _ Querier = (*Queries)(nil)
