// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: report.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createReport = `-- name: CreateReport :one
INSERT INTO reports (
    project_id, reporter_email, reporter_phone_number, reason, details
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, project_id, reporter_email, reporter_phone_number, reporter_fullname, reason, details, status, created_at
`

type CreateReportParams struct {
	ProjectID           uuid.UUID
	ReporterEmail       string
	ReporterPhoneNumber string
	Reason              string
	Details             string
}

func (q *Queries) CreateReport(ctx context.Context, arg CreateReportParams) (Report, error) {
	row := q.db.QueryRow(ctx, createReport,
		arg.ProjectID,
		arg.ReporterEmail,
		arg.ReporterPhoneNumber,
		arg.Reason,
		arg.Details,
	)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ReporterEmail,
		&i.ReporterPhoneNumber,
		&i.ReporterFullname,
		&i.Reason,
		&i.Details,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
