name: Build and deploy

on:
  pull_request:
    branches:
      - main 

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      IMAGE_BACKEND: ${{ secrets.DOCKERHUB_USERNAME }}/donorbox-backend
      IMAGE_CLIENT: ${{ secrets.DOCKERHUB_USERNAME }}/donorbox-client
      IMAGE_DASHBOARD: ${{ secrets.DOCKERHUB_USERNAME }}/donorbox-dashboard

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Dockerhub login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push backend
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.IMAGE_BACKEND }}:latest

      - name: Build and push client
        uses: docker/build-push-action@v5
        with:
          context: ./frontend/client
          file: ./frontend/client/Dockerfile
          push: true
          tags: ${{ env.IMAGE_CLIENT }}:latest
          build-args: |
            API_URL=${{ secrets.API_URL }}

      - name: Build and push dashboard
        uses: docker/build-push-action@v5
        with:
          context: ./frontend/escrow_dashboard
          file: ./frontend/escrow_dashboard/Dockerfile
          push: true
          tags: ${{ env.IMAGE_DASHBOARD }}:latest
          build-args: |
            API_URL=${{ secrets.API_URL }}
