name: Build and Test

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.22

      - name: Check out
        uses: actions/checkout@v4

      - name: Build
        run: go build -v ./...

      - name: go test -v ./...
