name: Test

on:
  pull_request:
    branches:
      - dev

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.20', '1.21', '1.22.x' ]
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Check out
        uses: actions/checkout@v4

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
